<?php
$modversion['name'] = "Xoops Teamspeak";
$modversion['version'] = "1.4";
$modversion['description'] = "Xoops Teamspeak";
$modversion['credits'] = "Gryphon, LLC www.gryphonllc.com";
$modversion['author'] = "Widowmaker";
$modversion['help'] = "None Available at this time.";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = "4.1.4 for TeamSpeak 2";
$modversion['image'] = "logo.gif";
$modversion['dirname'] = "xoops_teamspeak";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/xoops_teamspeak.sql";
// $modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "ts2_admin";
$modversion['tables'][1] = "ts2_channel";
$modversion['tables'][2] = "ts2_group";
$modversion['tables'][3] = "ts2_user";
$modversion['tables'][4] = "ts2_weblist";

// Admin things
$modversion['hasMain'] = 1;
$modversion['hasAdmin'] = 1;
$modversion['adminmenu'] = "admin/menu.php";

// Blocks

$modversion['blocks'][1]['file'] = "blocks.php";
$modversion['blocks'][1]['name'] = "Xoops Teamspeak";
$modversion['blocks'][1]['description'] = "Xoops Teamspeak";
$modversion['blocks'][1]['show_func'] = "xoopstslisting";
//$modversion['blocks'][1]['template'] = 'myxlinks.html';
?>
